import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const agentKey = v.union(v.literal("founder"), v.literal("research"), v.literal("landing_page"), v.literal("go_to_market"));
const commandStatus = v.union(v.literal("pending"), v.literal("running"), v.literal("succeeded"), v.literal("failed"));
const taskType = v.union(v.literal("orchestrate"), v.literal("create"), v.literal("peer_review"), v.literal("revise"), v.literal("synthesize"), v.literal("measure"));
const workflowStage = v.union(v.literal("discovery"), v.literal("research"), v.literal("research_ready"), v.literal("building"), v.literal("cross_review"), v.literal("launch_ready"), v.literal("launched"), v.literal("measuring"), v.literal("complete"));
const runTrace = v.object({ prompt: v.string(), attemptPrompts: v.array(v.string()), response: v.string(), model: v.union(v.string(), v.null()), provider: v.union(v.string(), v.null()), sessionIds: v.array(v.string()), inputTokens: v.number(), outputTokens: v.number(), cacheReadTokens: v.number(), cacheWriteTokens: v.number(), reasoningTokens: v.number(), estimatedCostUsd: v.number(), actualCostUsd: v.union(v.number(), v.null()), apiCallCount: v.number(), toolCallCount: v.number(), attemptCount: v.number() });

export default defineSchema({
  waitlist: defineTable({ email: v.string(), normalizedEmail: v.string(), createdAt: v.number(), source: v.string() }).index("by_normalized_email", ["normalizedEmail"]),
  companies: defineTable({ name: v.string(), ownerKey: v.optional(v.string()), website: v.optional(v.string()), createdAt: v.number() }).index("by_owner", ["ownerKey"]),
  agents: defineTable({ companyId: v.id("companies"), key: agentKey, name: v.string(), role: v.string(), status: v.union(v.literal("ready"), v.literal("working"), v.literal("error")), createdAt: v.number() }).index("by_company_key", ["companyId", "key"]),
  conversations: defineTable({ companyId: v.id("companies"), title: v.string(), status: v.union(v.literal("active"), v.literal("complete")), stage: v.optional(workflowStage), researchApprovedAt: v.optional(v.number()), launchApprovedAt: v.optional(v.number()), createdAt: v.number(), updatedAt: v.number() }).index("by_company", ["companyId"]),
  messages: defineTable({ conversationId: v.id("conversations"), role: v.union(v.literal("user"), v.literal("assistant")), agentKey: v.optional(agentKey), audience: v.optional(v.union(v.literal("user"), v.literal("internal"))), content: v.string(), createdAt: v.number() }).index("by_conversation_created", ["conversationId", "createdAt"]),
  agentRuns: defineTable({ conversationId: v.id("conversations"), commandId: v.id("workerCommands"), agentKey, taskType: v.optional(taskType), stage: v.optional(workflowStage), inputArtifactIds: v.optional(v.array(v.id("artifacts"))), parentRunId: v.optional(v.id("agentRuns")), reviewRound: v.optional(v.number()), status: commandStatus, summary: v.optional(v.string()), latencyMs: v.optional(v.number()), trace: v.optional(runTrace), error: v.optional(v.string()), synthesisQueuedAt: v.optional(v.number()), queuedAt: v.optional(v.number()), startedAt: v.number(), completedAt: v.optional(v.number()) }).index("by_conversation", ["conversationId"]).index("by_command", ["commandId"]),
  agentTraces: defineTable({ conversationId: v.id("conversations"), runId: v.id("agentRuns"), trace: runTrace, createdAt: v.number() }).index("by_run", ["runId"]).index("by_conversation", ["conversationId"]),
  artifacts: defineTable({ conversationId: v.id("conversations"), runId: v.id("agentRuns"), kind: v.string(), title: v.string(), content: v.string(), data: v.optional(v.any()), version: v.optional(v.number()), status: v.optional(v.union(v.literal("current"), v.literal("superseded"))), supersedesId: v.optional(v.id("artifacts")), sourceUrls: v.array(v.string()), createdAt: v.number() }).index("by_conversation", ["conversationId"]).index("by_conversation_status", ["conversationId", "status"]).index("by_conversation_kind", ["conversationId", "kind"]).index("by_run", ["runId"]),
  events: defineTable({ conversationId: v.id("conversations"), type: v.string(), detail: v.string(), createdAt: v.number() }).index("by_conversation_created", ["conversationId", "createdAt"]),
  workerCommands: defineTable({ conversationId: v.id("conversations"), agentKey, taskType: v.optional(taskType), stage: v.optional(workflowStage), inputArtifactIds: v.optional(v.array(v.id("artifacts"))), message: v.string(), rootRequest: v.optional(v.string()), reviewRound: v.optional(v.number()), context: v.array(v.object({ role: v.union(v.literal("user"), v.literal("assistant")), content: v.string() })), parentRunId: v.optional(v.id("agentRuns")), status: commandStatus, error: v.optional(v.string()), createdAt: v.number(), updatedAt: v.number() }).index("by_status", ["status"]),
  reviewFindings: defineTable({ conversationId: v.id("conversations"), runId: v.id("agentRuns"), reviewerAgent: agentKey, targetAgent: agentKey, targetArtifactId: v.optional(v.id("artifacts")), targetArtifactKind: v.string(), severity: v.union(v.literal("note"), v.literal("material"), v.literal("blocking")), feedback: v.string(), acceptanceCriteria: v.string(), round: v.number(), status: v.union(v.literal("open"), v.literal("resolved"), v.literal("accepted")), createdAt: v.number(), resolvedAt: v.optional(v.number()) }).index("by_conversation", ["conversationId"]).index("by_target", ["targetArtifactId"]),
  approvals: defineTable({ conversationId: v.id("conversations"), objectType: v.string(), objectId: v.string(), actor: v.union(v.literal("user"), v.literal("founder")), decision: v.union(v.literal("approved"), v.literal("rejected")), note: v.optional(v.string()), createdAt: v.number() }).index("by_conversation", ["conversationId"]).index("by_object", ["objectType", "objectId"]),
  campaigns: defineTable({ conversationId: v.id("conversations"), publicKey: v.string(), status: v.union(v.literal("draft"), v.literal("ready"), v.literal("live"), v.literal("paused"), v.literal("complete")), landingUrl: v.optional(v.string()), hypothesis: v.optional(v.string()), conversionEvent: v.optional(v.string()), createdAt: v.number(), updatedAt: v.number() }).index("by_conversation", ["conversationId"]).index("by_public_key", ["publicKey"]),
  waitlistLeads: defineTable({ campaignId: v.id("campaigns"), email: v.string(), normalizedEmail: v.string(), answer: v.optional(v.string()), utmSource: v.optional(v.string()), utmMedium: v.optional(v.string()), utmCampaign: v.optional(v.string()), utmContent: v.optional(v.string()), referrer: v.optional(v.string()), createdAt: v.number() }).index("by_campaign", ["campaignId"]).index("by_campaign_email", ["campaignId", "normalizedEmail"]),
  validationEvents: defineTable({ campaignId: v.id("campaigns"), type: v.union(v.literal("view"), v.literal("cta_click"), v.literal("form_start"), v.literal("signup"), v.literal("composer_opened")), platform: v.optional(v.string()), contentId: v.optional(v.string()), utmSource: v.optional(v.string()), utmMedium: v.optional(v.string()), utmCampaign: v.optional(v.string()), utmContent: v.optional(v.string()), referrer: v.optional(v.string()), visitorKey: v.optional(v.string()), createdAt: v.number() }).index("by_campaign", ["campaignId"]).index("by_campaign_type", ["campaignId", "type"]),
  rateLimits: defineTable({ key: v.string(), count: v.number(), expiresAt: v.number(), updatedAt: v.number() }).index("by_key", ["key"]),
});
